# Generated by Django 4.1 on 2022-08-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ct', models.CharField(max_length=120)),
                ('desc_ct', models.CharField(max_length=120)),
                ('imgct', models.ImageField(upload_to='categ')),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
