# Generated by Django 4.1 on 2022-08-27 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='categ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.category'),
        ),
    ]
